# Generated by Django 4.2 on 2023-04-24 09:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('amount', models.PositiveBigIntegerField()),
                ('category', models.CharField(choices=[('Housing', 'Housing'), ('Transportation', 'Transportation'), ('Groceries', 'Groceries'), ('Health Care', 'Health Care'), ('Entertainment', 'Entertainment'), ('Education', 'Education'), ('Personal Care', 'Personal Care'), ('Miscellaneous', 'Miscellaneous')], max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
